version: "3.9"
services:
  fake_vast_1:
    container_name: shepherd_fake_vast_1
    tty: true
    runtime: nvidia
    build:
      context: ./tools/vast
      dockerfile: fake_vast.Dockerfile

  fake_vast_2:
    container_name: shepherd_fake_vast_2
    tty: true
    runtime: nvidia
    build:
      context: ./tools/vast
      dockerfile: fake_vast.Dockerfile
  
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb_data_container:
