version: "3.9"
services:
  shepherd_fake_vast:
    container_name: shepherd_fake_vast
    tty: true
    runtime: nvidia
    build:
      context: ./vast
      dockerfile: fake_vast.Dockerfile
  
  shepherd_mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
