version: "3.9"
services:
  fake_vast_1:
    container_name: shepherd_fake_vast_1
    tty: true
    runtime: nvidia
    build:
      context: ./tools/vast
      dockerfile: fake_vast.Dockerfile

  fake_vast_2:
    container_name: shepherd_fake_vast_2
    tty: true
    runtime: nvidia
    build:
      context: ./tools/vast
      dockerfile: fake_vast.Dockerfile
  
  mongo:
    container_name: shepherd_mongo
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  redis:
    container_name: shepherd_redis
    image: redis:latest
    ports:
      - 6379:6379

  api:
    container_name: shepherd_api
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - 8080:8080
    # This env_file will be used, because godotenv does not override env variables by design.
    env_file:
      - .env.docker
    depends_on:
      - mongo
      - redis

  runner:
    container_name: shepherd_runner
    build:
      context: .
      dockerfile: ./cmd/runner/Dockerfile
    # This env_file will be used, because godotenv does not override env variables by design.
    env_file:
      - .env.docker
    depends_on:
      - mongo
      - redis

volumes:
  mongodb_data_container:
